# Generated by Django 3.2.9 on 2021-12-07 21:50

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20211207_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=martor.models.MartorField(default=''),
        ),
    ]
