# Generated by Django 3.2.9 on 2021-12-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_alter_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cover',
            field=models.ImageField(upload_to='media/Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
