# Generated by Django 3.2.9 on 2021-12-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_auto_20211208_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mens_products', "Men's Products"), ('Womens_products', "Women's Products"), ('Accessories', 'Accessories'), ('Kids_products', "Kids' Products")], default='Others', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sale')], max_length=30, null=True),
        ),
    ]
