# Generated by Django 3.2.9 on 2021-12-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_auto_20211228_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sale'), ('Discount', 'Discount')], max_length=30, null=True),
        ),
    ]
