# Generated by Django 3.2.9 on 2021-12-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_alter_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mens_products', "Men's Products"), ('Womens_products', "Women's Products"), ('Accessories', 'Accessories'), ('Home_products', 'Home Products')], default='Others', max_length=30),
        ),
    ]
