# Generated by Django 3.2.9 on 2021-12-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Sale', 'Sale'), ('Discount', 'Discount')], max_length=30, null=True),
        ),
    ]
