# Generated by Django 3.2.9 on 2021-12-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0012_auto_20211230_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallary',
            name='slug',
        ),
    ]
