# Generated by Django 3.2.9 on 2021-12-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0013_remove_productgallary_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallary',
            name='images',
            field=models.ImageField(upload_to='media/Product_gallary'),
        ),
    ]
